## Как создавать и сравнивать датафреймы

In [1]:
import pandas as pd

In [34]:
d = {
    'name': ['Andron', 'Liza', 'Nikita'],
    'color': ['green', 'red', 'blue']
}

pd.DataFrame(d)

     name  color
0  Andron  green
1    Liza    red
2  Nikita   blue

In [37]:
a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

pd.DataFrame(a, columns=['A', 'B', 'C'])

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [38]:
d = {
    'name': ['Andron', 'Liza', 'Nikita'],
    'color': ['green', 'red', 'blue']
}

d1 = pd.DataFrame(d)
d2 = pd.DataFrame(d)

In [41]:
(d1 == d2).all()

name     True
color    True
dtype: bool

In [40]:
d1.equals(d2)

True

## Как создать случайную выборку

In [4]:
import pandas as pd

In [6]:
from pathlib import Path
# Папка, где находится текущий скрипт/ноутбук
base_dir = Path('C:/Users/MACHENIKE/VadimLearn/Vadim-Learn/data').parent  # для .py файлов
# или если вы в Jupyter:
# base_dir = Path.cwd()
file_path = base_dir / 'data' / 'data.csv'

In [7]:
df = pd.read_csv(file_path, encoding='1251')

In [8]:
df.sample(3)

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,...,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
4081,2022-08-12,20:17:31,4437,18002543,18,9906,Розничная реализация,15,24981,ДОМАШ.АПТЕЧКА СУПЕРЧИСТОТЕЛО 3МЛ. №1,...,ДВЕ ЛИНИИ ООО ПКФ,1.0,24.38,40.0,0.0,NaN,NaN,54,1,1.0
2180,2022-08-11,09:23:02,4645,11007004,11,23925,Розничная реализация,15,317995,ФУРАЗОЛИДОН АВЕКСИМА 50МГ. №20 ТАБ. /ИРБИТСКИЙ/,...,Авексима ОАО,1.0,108.69,152.0,10.0,9.0,2.000100e+11,30,1,3.0
2677,2022-08-12,14:47:00,2269,2004623,2,22577,Розничная реализация,18,19546,"РИНОСТОП 0,1% 10МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /ОТИС...",...,ОТИСИФАРМ ПАО,1.0,25.69,32.0,1.0,9.0,2.000100e+11,205,1,4.0

## Как совместить ABC- и XYZ-анализы

In [50]:
abc = pd.DataFrame({
    'name': ['кабачок', 'помидор', 'огурец'],
    'abc': ['A', 'A', 'C']
})

xyz = pd.DataFrame({
    'name_xyz': ['кабачок', 'баклажан', 'огурец'],
    'xyz': ['X', 'Y', 'Z']
})

In [55]:
abc_xyz = abc.merge(xyz, left_on='name', right_on='name_xyz', how='outer')
abc_xyz

      name  abc  name_xyz  xyz
0  кабачок    A   кабачок    X
1  помидор    A       NaN  NaN
2   огурец    C    огурец    Z
3      NaN  NaN  баклажан    Y

In [56]:
import numpy as np

In [58]:
abc_xyz['name'] = np.where(abc_xyz['name'].isnull(), abc_xyz['name_xyz'], abc_xyz['name'])
abc_xyz

       name  abc  name_xyz  xyz
0   кабачок    A   кабачок    X
1   помидор    A       NaN  NaN
2    огурец    C    огурец    Z
3  баклажан  NaN  баклажан    Y

In [64]:
abc_xyz = abc_xyz.drop('name_xyz', axis=1)

In [65]:
abc_xyz

       name  abc  xyz
0   кабачок    A    X
1   помидор    A  NaN
2    огурец    C    Z
3  баклажан  NaN    Y

## Как фильтровать данные

In [70]:
df.filter(like='ug', axis=1)

      DR_CDrugs                                          DR_NDrugs
0         45399  ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...
1        261519            ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.
2        460864  СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...
3        172823  СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...
4         79056                   ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/
...         ...                                                ...
4457     463100  КЕТОРОЛ ЭКСПРЕСС 10МГ. №20 ТАБ. ДИСПЕРГ. /Д-Р ...
4458     112158                           АНТИПОЛИЦАЙ ВАЙТ №6 ТАБ.
4459     260990  СИЛДЕНАФИЛ-СЗ 50МГ. №10 ТАБ. П/П/О /СЕВЕРНАЯ З...
4460      41512                         ТОБРАЗОН 5МЛ. ГЛ.КАПЛИ ФЛ.
4461      25673  БЕЛЬВЕДЕР ЛАК П/ОБГРЫЗАНИЯ НОГТЕЙ 8МЛ. [BELWEDER]

[4462 rows x 2 columns]

## Как один датафрейм разбить на несколько

In [9]:
shops = df['DR_Apt'].unique().tolist()

In [ ]:
# ModuleNotFoundError: No module named 'openpyxl'

In [12]:
import openpyxl

In [15]:
for shop in shops:
    small_df = df[df['DR_Apt'] == shop]
    small_df.to_excel(f'extra/{shop}.xlsx', sheet_name=f'{shop}', index=False)

In [88]:
pd.read_excel('extra/2.xlsx')

,DR_Dat,DR_Tim,DR_NChk,DR_NDoc,DR_Apt,DR_Kkm,DR_TDoc,DR_TPay,DR_CDrugs,DR_NDrugs,...,DR_Prod,DR_Kol,DR_CZak,DR_CRoz,DR_SDisc,DR_CDisc,DR_BCDisc,DR_TabEmpl,DR_VZak,DR_Pos
0,2022-08-11,10:15:35,2173,2004598,2,22577,Розничная реализация,18,45399,ЦИПРОЛЕТ 3МГ/МЛ. 5МЛ. №1 ГЛ.КАПЛИ ФЛ./КАП. /Д-...,...,Д-р Редди с Лабораторис Лтд / Dr.REDDY's,1.0,41.08,51.0,12.00,925.0,2.000000e+11,205,1,1
1,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,261519,ПЕРЕКИСЬ ВОДОРОДА 3% 100МЛ. №40 Р-Р ФЛ.,...,ФЛОРА КАВКАЗА ОАО,1.0,18.61,31.0,3.00,9.0,2.000100e+11,205,1,1
2,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,460864,СОФЬЯ ГЕЛЬ Д/НОГ ВЕНОТОНИЗ. ТРОКСЕРУТИН ФОРТЕ ...,...,КОРОЛЕВФАРМ ООО,1.0,132.69,209.0,20.00,9.0,2.000100e+11,205,1,2
3,2022-08-11,10:27:46,2174,2004598,2,22577,Розничная реализация,15,172823,СОФЬЯ ГХК КРЕМ Д/ТЕЛА ХОНДРОИТИН+ГЛЮКОЗАМИН 12...,...,КОРОЛЕВФАРМ ООО,1.0,133.65,210.0,21.00,9.0,2.000100e+11,205,1,3
4,2022-08-11,10:33:56,2175,2004598,2,22577,Розничная реализация,18,79056,ГАЛВУС 50МГ. №28 ТАБ. /НОВАРТИС/,...,Новартис Фарма АГ,1.0,709.95,787.0,49.00,925.0,2.000000e+11,205,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
974,2022-08-12,20:45:40,8489,2004621,2,22569,Розничная реализация,15,28345,АЛЬПИНА СПРИНЦОВКА ПВХ №7Б ТВЕРД.НАКОН. ПЛАСТИ...,...,АЛЬПИНА ПЛАСТ ООО,1.0,112.90,178.0,0.00,NaN,NaN,123,1,1
975,2022-08-12,20:45:40,8489,2004621,2,22569,Розничная реализация,15,490990,СИЛЬВЕР КАПИТАН БАТОНЧИК КОКОС ВАР.СГУЩ.+ЙОГУР...,...,ФАКЕЛ-ДИЗАЙН ООО,2.0,24.48,40.0,0.00,NaN,NaN,123,1,10
976,2022-08-12,20:45:40,8489,2004621,2,22569,Розничная реализация,15,337422,АСКОРБИНКА ВИТАМИН С 25МГ. ДЕТСК. 3Г. №10 ТАБ....,...,ФАРМГРУПП,1.0,8.41,14.0,0.00,NaN,NaN,123,1,2
977,2022-08-12,20:51:41,8490,2004621,2,22569,Розничная реализация,18,4146,ТОТЕМА 10МЛ. №20 Р-Р Д/ПРИЕМА ВНУТРЬ АМП.,...,Иннотера Шузи (INNOTERA),1.0,565.69,775.0,97.21,925.0,2.000000e+11,123,1,3
978,2022-08-12,20:51:41,8490,2004621,2,22569,Розничная реализация,18,14781,ГЕМАТОГЕН РУССКИЙ КОКОС В ГЛАЗУРИ 40Г. ПЛИТКА ...,...,ФАРМ-ПРО,1.0,14.44,24.0,3.01,925.0,2.000000e+11,123,1,2

## Как объединить датафреймы

In [89]:
import glob

In [91]:
glob.glob('extra/*.xlsx')

['extra\\11.xlsx',
 'extra\\13.xlsx',
 'extra\\15.xlsx',
 'extra\\17.xlsx',
 'extra\\18.xlsx',
 'extra\\2.xlsx',
 'extra\\6.xlsx',
 'extra\\7.xlsx']

In [92]:
files = glob.glob('extra/*.xlsx')

dfs = []

for file_name in files:
    small_df = pd.read_excel(file_name)
    dfs.append(small_df)

In [94]:
len(dfs)

8

In [96]:
df = pd.concat(dfs, ignore_index=True)

## Как делать преобразования внутри датафреймов

In [101]:
for i, row in df.iterrows():
    s = f"insert into sales values ('{row['DR_Dat']}', '{row['DR_Kol']}')"
    print(s)
    # print(f'Номер строки: {i}, дата: {row["DR_Dat"]}')
    if i == 10:
        break

insert into sales values ('2022-08-11', '1.0')
insert into sales values ('2022-08-11', '1.0')
insert into sales values ('2022-08-11', '1.0')
insert into sales values ('2022-08-11', '1.0')
insert into sales values ('2022-08-11', '1.0')
insert into sales values ('2022-08-11', '1.0')
insert into sales values ('2022-08-11', '1.0')
insert into sales values ('2022-08-11', '1.0')
insert into sales values ('2022-08-11', '1.0')
insert into sales values ('2022-08-11', '1.0')
insert into sales values ('2022-08-11', '1.0')